MDS-115 [ADD] Reimpliment Logging Class
medusa-framework/medusa pull request #11
Opened 2023-04-03 13:59 UTC by justinelinette

# [MDS-115](https://jacobfholland.atlassian.net/browse/MDS-115)
### Author: @justinelinette 
### Date: 4/3/2023

### Description: 
Reimplement logging class

### Implementation: 
None

2023-04-03 15:02 UTC, jacobfholland requested changes
I have given it a review. Really great job for totally doing it on your own. I have marked some requested changes for you.

2023-04-03 15:02 UTC, jacobfholland commented on medusa/__init__.py
> +            os.makedirs("logs")
Are we sure we want to include `logs` directory directly in the `medusa` folder? Should it not live outside of `medusa` where our `scripts` folder already is? This is a design decision and your call. Though I think it should be outside the medusa package.

2023-04-04 22:16 UTC, justinelinette commented on medusa/config/app.py
> +    LOG_PATH = "logs/mds.log"
log path split into log name, log path, log file

2023-04-04 22:20 UTC, justinelinette commented on medusa/log/log.py
> +        self.logger.debug(built_message)
made these changes for all logging methods

2023-04-05 01:17 UTC, jacobfholland approved these changes

2023-04-05 01:17 UTC, merged